### ISSUE TITLE
availableMoves Highlight and Gameboard Space Colors are indistinguishable

### ISSUE THREAD

**Issue by shredd** [shredd/CS451Project#77]
We need strong and distinct colors for the gameboard squares and for the availableMoves highlight.

Gameboard can be black a white squares and available moves can be grey highlights of some sort. The focus here should be usability, it is nearly impossible to distinguish these features on a mobile device with the brightness turned down.

![img_3490](https://user-images.githubusercontent.com/12621035/37265126-be22646a-2587-11e8-8502-243dfbd25d46.PNG)

**Comment by prokhorvlg** [comment]
Fixed visibility issues.
